language: ruby
rvm:
  - 2.4.3
services:
  - postgresql
before_script:
  - cp config/database.yml.travis database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
addons:
  postgresql: "9.5"
